version: "3.9"

services:
  api:
    build:
      context: ./api
    image: thibaultferaux/industry-project-roof-detection-api
    ports:
      - 8000:8000
    volumes:
      - ./api/results.json:/mnt/data/results.json
